jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Copy CNAME and static files
        run: cp public/CNAME docs/CNAME

      - name: Build site
        run: npm run build

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          entryPoint: "docs/index.html"
          path-to-root: "docs"
          base-url-path: "/"
          include-html: true
          sitemap-format: "xml"

      - name: Commit sitemap and CNAME
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update sitemap and ensure CNAME"
          file_pattern: "docs/sitemap.xml,docs/CNAME"