name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: "docs"
          base-url-path: "/"
          include-html: true
          sitemap-format: "xml"

      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update sitemap"
          file_pattern: "docs/sitemap.xml"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          commit_user_email: "actions@github.com"
          commit_user_name: "GitHub Actions"
          # Prevent workflow loop:
          skip_ci: true
